// Package listings provides primitives to interact the openapi HTTP API.
//
// Code generated by go-sdk-codegen DO NOT EDIT.
package listings

import (
	"encoding/json"
	"fmt"
	"time"

	"github.com/pkg/errors"
)

// Decimal defines model for Decimal.
type Decimal string

// Error defines model for Error.
type Error struct {

	// An error code that identifies the type of error that occurred.
	Code string `json:"code"`

	// Additional details that can help the caller understand or fix the issue.
	Details *string `json:"details,omitempty"`

	// A message that describes the error condition.
	Message string `json:"message"`
}

// ErrorList defines model for ErrorList.
type ErrorList struct {
	Errors []Error `json:"errors"`
}

// FulfillmentAvailability defines model for FulfillmentAvailability.
type FulfillmentAvailability struct {

	// Designates which fulfillment network will be used.
	FulfillmentChannelCode string `json:"fulfillmentChannelCode"`

	// The quantity of the item you are making available for sale.
	Quantity *int `json:"quantity,omitempty"`
}

// Issue defines model for Issue.
type Issue struct {

	// Names of the attributes associated with the issue, if applicable.
	AttributeNames *[]string `json:"attributeNames,omitempty"`

	// An issue code that identifies the type of issue.
	Code string `json:"code"`

	// A message that describes the issue.
	Message string `json:"message"`

	// The severity of the issue.
	Severity string `json:"severity"`
}

// Item defines model for Item.
type Item struct {

	// JSON object containing structured listings item attribute data keyed by attribute name.
	Attributes *ItemAttributes `json:"attributes,omitempty"`

	// Fulfillment availability for the listings item.
	FulfillmentAvailability *[]FulfillmentAvailability `json:"fulfillmentAvailability,omitempty"`

	// Issues associated with the listings item.
	Issues *ItemIssues `json:"issues,omitempty"`

	// Offer details for the listings item.
	Offers *ItemOffers `json:"offers,omitempty"`

	// Vendor procurement information for the listings item.
	Procurement *ItemProcurement `json:"procurement,omitempty"`

	// A selling partner provided identifier for an Amazon listing.
	Sku string `json:"sku"`

	// Summary details of a listings item.
	Summaries *ItemSummaries `json:"summaries,omitempty"`
}

// ItemAttributes defines model for ItemAttributes.
type ItemAttributes struct {
	AdditionalProperties map[string]interface{} `json:"-"`
}

// ItemImage defines model for ItemImage.
type ItemImage struct {

	// Height of the image in pixels.
	Height int `json:"height"`

	// Link, or URL, for the image.
	Link string `json:"link"`

	// Width of the image in pixels.
	Width int `json:"width"`
}

// ItemIssues defines model for ItemIssues.
type ItemIssues []Issue

// ItemOfferByMarketplace defines model for ItemOfferByMarketplace.
type ItemOfferByMarketplace struct {

	// Amazon marketplace identifier.
	MarketplaceId string `json:"marketplaceId"`

	// Type of offer for the listings item.
	OfferType string `json:"offerType"`

	// The number of Amazon Points offered with the purchase of an item, and their monetary value. Note that the Points element is only returned in Japan (JP).
	Points *Points `json:"points,omitempty"`

	// The currency type and the amount.
	Price Money `json:"price"`
}

// ItemOffers defines model for ItemOffers.
type ItemOffers []ItemOfferByMarketplace

// ItemProcurement defines model for ItemProcurement.
type ItemProcurement struct {

	// The currency type and the amount.
	CostPrice Money `json:"costPrice"`
}

// ItemSummaries defines model for ItemSummaries.
type ItemSummaries []ItemSummaryByMarketplace

// ItemSummaryByMarketplace defines model for ItemSummaryByMarketplace.
type ItemSummaryByMarketplace struct {

	// Amazon Standard Identification Number (ASIN) of the listings item.
	Asin string `json:"asin"`

	// Identifies the condition of the listings item.
	ConditionType *string `json:"conditionType,omitempty"`

	// Date the listings item was created, in ISO 8601 format.
	CreatedDate time.Time `json:"createdDate"`

	// Fulfillment network stock keeping unit is an identifier used by Amazon fulfillment centers to identify each unique item.
	FnSku *string `json:"fnSku,omitempty"`

	// Name, or title, associated with an Amazon catalog item.
	ItemName string `json:"itemName"`

	// Date the listings item was last updated, in ISO 8601 format.
	LastUpdatedDate time.Time `json:"lastUpdatedDate"`

	// Image for the listings item.
	MainImage *ItemImage `json:"mainImage,omitempty"`

	// A marketplace identifier. Identifies the Amazon marketplace for the listings item.
	MarketplaceId string `json:"marketplaceId"`

	// The Amazon product type of the listings item.
	ProductType string `json:"productType"`

	// Statuses that apply to the listings item.
	Status []string `json:"status"`
}

// ListingsItemPatchRequest defines model for ListingsItemPatchRequest.
type ListingsItemPatchRequest struct {

	// One or more JSON Patch operations to perform on the listings item.
	Patches []PatchOperation `json:"patches"`

	// The Amazon product type of the listings item.
	ProductType string `json:"productType"`
}

// ListingsItemPutRequest defines model for ListingsItemPutRequest.
type ListingsItemPutRequest struct {

	// JSON object containing structured listings item attribute data keyed by attribute name.
	Attributes ListingsItemPutRequest_Attributes `json:"attributes"`

	// The Amazon product type of the listings item.
	ProductType string `json:"productType"`

	// The name of the requirements set for the provided data.
	Requirements *string `json:"requirements,omitempty"`
}

// ListingsItemPutRequest_Attributes defines model for ListingsItemPutRequest.Attributes.
type ListingsItemPutRequest_Attributes struct {
	AdditionalProperties map[string]interface{} `json:"-"`
}

// ListingsItemSubmissionResponse defines model for ListingsItemSubmissionResponse.
type ListingsItemSubmissionResponse struct {

	// Listings item issues related to the listings item submission.
	Issues *[]Issue `json:"issues,omitempty"`

	// A selling partner provided identifier for an Amazon listing.
	Sku string `json:"sku"`

	// The status of the listings item submission.
	Status string `json:"status"`

	// The unique identifier of the listings item submission.
	SubmissionId string `json:"submissionId"`
}

// Money defines model for Money.
type Money struct {

	// A decimal number with no loss of precision. Useful when precision loss is unnaceptable, as with currencies. Follows RFC7159 for number representation.
	Amount Decimal `json:"amount"`

	// Three-digit currency code. In ISO 4217 format.
	CurrencyCode string `json:"currencyCode"`
}

// PatchOperation defines model for PatchOperation.
type PatchOperation struct {

	// Type of JSON Patch operation. Supported JSON Patch operations include add, replace, and delete. See <https://tools.ietf.org/html/rfc6902>.
	Op string `json:"op"`

	// JSON Pointer path of the element to patch. See <https://tools.ietf.org/html/rfc6902>.
	Path string `json:"path"`

	// JSON value to add, replace, or delete.
	Value *[]struct {
		AdditionalProperties map[string]interface{} `json:"-"`
	} `json:"value,omitempty"`
}

// Points defines model for Points.
type Points struct {
	PointsNumber int `json:"pointsNumber"`
}

// DeleteListingsItemParams defines parameters for DeleteListingsItem.
type DeleteListingsItemParams struct {

	// A comma-delimited list of Amazon marketplace identifiers for the request.
	MarketplaceIds []string `json:"marketplaceIds"`

	// A locale for localization of issues. When not provided, the default language code of the first marketplace is used. Examples: "en_US", "fr_CA", "fr_FR". Localized messages default to "en_US" when a localization is not available in the specified locale.
	IssueLocale *string `json:"issueLocale,omitempty"`
}

// GetListingsItemParams defines parameters for GetListingsItem.
type GetListingsItemParams struct {

	// A comma-delimited list of Amazon marketplace identifiers for the request.
	MarketplaceIds []string `json:"marketplaceIds"`

	// A locale for localization of issues. When not provided, the default language code of the first marketplace is used. Examples: "en_US", "fr_CA", "fr_FR". Localized messages default to "en_US" when a localization is not available in the specified locale.
	IssueLocale *string `json:"issueLocale,omitempty"`

	// A comma-delimited list of data sets to include in the response. Default: summaries.
	IncludedData *[]string `json:"includedData,omitempty"`
}

// PatchListingsItemJSONBody defines parameters for PatchListingsItem.
type PatchListingsItemJSONBody ListingsItemPatchRequest

// PatchListingsItemParams defines parameters for PatchListingsItem.
type PatchListingsItemParams struct {

	// A comma-delimited list of Amazon marketplace identifiers for the request.
	MarketplaceIds []string `json:"marketplaceIds"`

	// A locale for localization of issues. When not provided, the default language code of the first marketplace is used. Examples: "en_US", "fr_CA", "fr_FR". Localized messages default to "en_US" when a localization is not available in the specified locale.
	IssueLocale *string `json:"issueLocale,omitempty"`
}

// PutListingsItemJSONBody defines parameters for PutListingsItem.
type PutListingsItemJSONBody ListingsItemPutRequest

// PutListingsItemParams defines parameters for PutListingsItem.
type PutListingsItemParams struct {

	// A comma-delimited list of Amazon marketplace identifiers for the request.
	MarketplaceIds []string `json:"marketplaceIds"`

	// A locale for localization of issues. When not provided, the default language code of the first marketplace is used. Examples: "en_US", "fr_CA", "fr_FR". Localized messages default to "en_US" when a localization is not available in the specified locale.
	IssueLocale *string `json:"issueLocale,omitempty"`
}

// PatchListingsItemRequestBody defines body for PatchListingsItem for application/json ContentType.
type PatchListingsItemJSONRequestBody PatchListingsItemJSONBody

// PutListingsItemRequestBody defines body for PutListingsItem for application/json ContentType.
type PutListingsItemJSONRequestBody PutListingsItemJSONBody

// Getter for additional properties for ItemAttributes. Returns the specified
// element and whether it was found
func (a ItemAttributes) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ItemAttributes
func (a *ItemAttributes) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ItemAttributes to handle AdditionalProperties
func (a *ItemAttributes) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return errors.Wrap(err, fmt.Sprintf("error unmarshaling field %s", fieldName))
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ItemAttributes to handle AdditionalProperties
func (a ItemAttributes) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, errors.Wrap(err, fmt.Sprintf("error marshaling '%s'", fieldName))
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for ListingsItemPutRequest_Attributes. Returns the specified
// element and whether it was found
func (a ListingsItemPutRequest_Attributes) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ListingsItemPutRequest_Attributes
func (a *ListingsItemPutRequest_Attributes) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ListingsItemPutRequest_Attributes to handle AdditionalProperties
func (a *ListingsItemPutRequest_Attributes) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return errors.Wrap(err, fmt.Sprintf("error unmarshaling field %s", fieldName))
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ListingsItemPutRequest_Attributes to handle AdditionalProperties
func (a ListingsItemPutRequest_Attributes) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, errors.Wrap(err, fmt.Sprintf("error marshaling '%s'", fieldName))
		}
	}
	return json.Marshal(object)
}
